version: 2.1
orbs:
  browser-tools: circleci/browser-tools@1.2.3
jobs:
  run-unit-tests:
    parallelism: 1
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout
      - run:
          name: Install Tools
          command: /home/circleci/project/.circleci/support.sh install-tools
      - run:
          name: Build Flow
          command:  |
            /home/circleci/project/scripts/computeMatrix.js set-version --version=999.99-SNAPSHOT
            # mvn -B -q -DnewVersion=999.99-SNAPSHOT versions:set  -T 1C
            mvn -B -DskipTests install -T 2C -q -pl \!flow-plugins/flow-gradle-plugin
      - run:
          name: Run Unit Tests
          command:  |
            args=`/home/circleci/project/scripts/computeMatrix.js unit-tests --parallel=$CIRCLE_NODE_TOTAL --container=$CIRCLE_NODE_INDEX`
            set -x
            mvn test -V -B -e -q \
              $args
      - run:
          name: Save test results
          command: |
            mkdir -p test-results
            find . -type f -regex ".*/target/.*-reports/.*xml" -exec cp '{}' test-results ';'
          when: always
      - store_test_results:
          path: test-results
  run-it-tests:
    parallelism: 9
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - run:
          name: Install Tools
          command: /home/circleci/project/.circleci/support.sh install-tools
      - run:
          name: Build Flow
          command:  |
            echo ">>> Setting version .... " >&2
            time /home/circleci/project/scripts/computeMatrix.js set-version --version=999.99-SNAPSHOT
            mvn -B -q -DnewVersion=999.99-SNAPSHOT versions:set  -T 1C
            echo ">>> Building flow .... " >&2
            time mvn -B -q -DskipTests install -T 2C -pl \!flow-plugins/flow-gradle-plugin
      - run:
          name: Build Shared Modules
          command:  |
            time mvn -B install -DskipTests -Pit-shared-modules,it-shared-spring-modules -amd -pl flow-tests
      - run:
          name: Run Integration Tests
          command:  |
            echo ">>> Testing Modules" >&2
            args=`/home/circleci/project/scripts/computeMatrix.js it-tests --parallel=$CIRCLE_NODE_TOTAL --container=$CIRCLE_NODE_INDEX`
            set -x
            mvn verify -V -B -e -fae \
              -Dcom.vaadin.testbench.Parameters.testsInParallel=4 \
              -Dfailsafe.rerunFailingTestsCount=2 \
              -Dmaven.wagon.httpconnectionManager.ttlSeconds=25 \
              -Dmaven.wagon.http.retryHandler.count=3 \
              $args
      - run:
          name: Save test results
          command: |
            mkdir -p test-results
            find . -type f -regex ".*/target/.*-reports/.*xml" -exec cp '{}' test-results ';'
          when: always
      - store_test_results:
          path: test-results
workflows:
  build-and-test:
    jobs:
      - run-unit-tests
      - run-it-tests

