name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - uses: stCarolas/setup-maven@v4.2
        with:
          maven-version: 3.8.3
      - name: mvn install
        run: |
          mvn -B -q -DnewVersion=999.99-SNAPSHOT versions:set  -T 1C
          mvn install -B -q -am -DskipTests -T 2C
      - name: Save workspace
        run: |
          mv ~/.m2/ .
          tar cf workspace.tar .m2 `find . -d -name target`
      - uses: actions/upload-artifact@v2
        with:
          name: saved-workspace
          path: workspace.tar
  unit-test:
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        modules:
          - 'flow-server'
          - 'flow-client,vaadin-dev-server'
          - 'flow-data'
          - 'build-tools,flow,flow-bom,flow-component-demo-helpers,flow-dnd,flow-html-components,flow-html-components-testbench,flow-lit-template,flow-plugins,flow-polymer-template,flow-push,flow-server-production-mode,flow-test-generic,flow-test-util,fusion-endpoint'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - uses: stCarolas/setup-maven@v4.2
        with:
          maven-version: 3.8.3
      - uses: actions/download-artifact@v2
        with:
          name: saved-workspace
      - name: Restore Workspace
        run: |
          tar xf workspace.tar
          rm -rf ~/.m2 && mv -f .m2 ~/
      - name: Unit Test
        if: always()
        run: |
          mvn -B -q -DnewVersion=999.99-SNAPSHOT versions:set  -T 1C
          mvn -B test -fae -pl ${{ matrix.modules }}
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: test-reports
          path: "**/target/*-reports/*"
  install:
    if: ${{ false }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Chrome
        run: |
          sudo apt-get update
          wget -q https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt-get install -y -f ./google-chrome-stable_current_amd64.deb
      - uses: nanasess/setup-chromedriver@master
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Set up Maven
        uses: stCarolas/setup-maven@v4.2
        with:
          maven-version: 3.8.3
      - name: Show Tool Versions
        run: |
          java -version
          mvn -version
          echo "Node "`node --version`
          echo "Npm "`npm -version`
          google-chrome --version
          chromedriver --version
          pwd
          ls -al
      - name: Build with Maven
        if: always()
        run: |
          mvn -B -q -DnewVersion=999.99-SNAPSHOT versions:set  -T 1C
          mvn -B -q -DskipTests install -T 2C
  publish-test-results:
    needs: unit-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: test-reports
      - name: Publish Unit Test Results
        if: always()
        uses: EnricoMi/publish-unit-test-result-action/composite@v1
        with:
          files: "**/target/*-reports/*.xml"
