name: Java CI

on: [push]

jobs:
  matrix-unit-test:
    if: always()
    runs-on: ubuntu-latest
    strategy:
      matrix:
        modules:
          - 'flow-server'
          - 'flow-client'
          - 'flow-data'
          - 'vaadin-dev-server'
          - 'build-tools,flow,flow-bom,flow-component-demo-helpers,flow-dnd,flow-html-components,flow-html-components-testbench,flow-lit-template,flow-plugins,flow-polymer-template,flow-push,flow-server-production-mode,flow-test-generic,flow-test-util,fusion-endpoint'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - uses: stCarolas/setup-maven@v4.2
        with:
          maven-version: 3.8.3      
      - name: Show Tool Versions
        run: |
          java -version
          mvn -version
          echo "Node "`node --version`
          echo "Npm "`npm -version`
      - name: Compile Modules
        if: always()
        run: |
          mvn -B -q -DnewVersion=999.99-SNAPSHOT versions:set  -T 1C
          mvn -B -q -DskipTests install -T 2C
      - name: Unit Test
        if: always()
        run: |
          mvn -B test -fae -pl ${{ matrix.modules }}
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: test-reports
          path: "**/target/*-reports/*"
  unit-test:
    if: ${{ false }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - uses: stCarolas/setup-maven@v4.2
        with:
          maven-version: 3.8.3      
      - name: Show Tool Versions
        run: |
          java -version
          mvn -version
          echo "Node "`node --version`
          echo "Npm "`npm -version`
      - name: Unit Test
        run: |
          mvn -B -q -DnewVersion=999.99-SNAPSHOT versions:set  -T 1C
          mvn -B -am -q -pl flow-server test
      - name: Publish Unit Test Results
        if: always()
        uses: EnricoMi/publish-unit-test-result-action/composite@v1
        with:
          files: "**/target/*-reports/*.xml"
  install:
    if: ${{ false }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Chrome
        run: |
          sudo apt-get update
          wget -q https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt-get install -y -f ./google-chrome-stable_current_amd64.deb
      - uses: nanasess/setup-chromedriver@master
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Set up Maven
        uses: stCarolas/setup-maven@v4.2
        with:
          maven-version: 3.8.3
      - name: Show Tool Versions
        run: |
          java -version
          mvn -version
          echo "Node "`node --version`
          echo "Npm "`npm -version`
          google-chrome --version
          chromedriver --version
          pwd
          ls -al
      - name: Build with Maven
        if: always()
        run: |
          mvn -B -q -DnewVersion=999.99-SNAPSHOT versions:set  -T 1C
          mvn -B -q -DskipTests install -T 2C

  publish-test-results:
    if: always()
    needs: matrix-unit-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: test-reports
      - name: Display structure of downloaded files
        run: ls -R
      - name: Publish Unit Test Results
        if: always()
        uses: EnricoMi/publish-unit-test-result-action/composite@v1
        with:
          files: "**/target/*-reports/*.xml"          


# - uses: nanasess/setup-chromedriver@master
#   with:
#     # Optional: do not specify to match Chrome's version
#     chromedriver-version: '88.0.4324.96'
# - run: |
#     export DISPLAY=:99
#     chromedriver --url-base=/wd/hub &
#     sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 & # optional